common:
  name: conv
  domain: conv.test
  protocol: http
  registry: antonlarichev

app:
  replicas: 1
  name: app
  image: conv-app
  tag: 1.2
  targetPort: 80
  port: 3000
  component: frontend

api:
  name: api
  targetPort: 3000
