apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.common.name }}-{{ .Values.app.name }}-clusterip"
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.app.component }}
  ports:
  - port: {{ .Values.app.port }}
    targetPort: {{ .Values.app.targetPort }}
