apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.common.name }}-{{ .Values.app.name }}-deployment"
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.app.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.app.component }}
    spec:
      containers:
      - name: "{{ .Values.common.name }}-{{ .Values.app.name }}-deployment"
        image: "{{ .Values.common.registry }}/{{ .Values.app.image }}:{{ .Values.app.tag }}"
        env:
          - name: VITE_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: "{{ .Values.common.name }}-{{ .Values.app.name }}-configmap"
                key: VITE_DOMAIN
        resources:
          limits: {{ .Values.app.limits | toYaml | nindent 12 }}
        ports:
        - containerPort: {{ .Values.app.targetPort }}
