apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.common.name }}-{{ .Values.app.name }}-configmap"
data:
  VITE_DOMAIN:  "{{ .Values.common.protocol }}://{{ .Values.common.domain }}"
