apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.common.name }}-{{ .Values.processor.name }}-deployment"
spec:
  replicas: {{ .Values.processor.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.processor.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.processor.component }}
    spec:
      containers:
      - name: "{{ .Values.common.name }}-{{ .Values.processor.name }}-deployment"
        image: "{{ .Values.common.registry }}/{{ .Values.processor.image }}:{{ .Values.processor.tag }}"
        env:
          {{- range .Values.processor.envs  }}
          {{- $data := dict "name" $.Values.common.name "env" . }}
          {{- include "env.template" $data | indent 10}}
          {{- end }}
        resources:
          limits: {{ .Values.processor.limits | toYaml | nindent 12 }}
        ports:
        - containerPort: {{ .Values.processor.targetPort }}
