apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.common.name }}-{{ .Values.api.name }}-deployment"
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.api.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.api.component }}
    spec:
      containers:
      - name: "{{ .Values.common.name }}-{{ .Values.api.name }}-deployment"
        image: "{{ .Values.common.registry }}/{{ .Values.api.image }}:{{ .Values.api.tag }}"
        env:
          {{- range .Values.api.envs  }}
          {{- $data := dict "name" $.Values.common.name "env" . }}
          {{- include "env.template" $data | indent 10}}
          {{- end }}
        volumeMounts:
          - name: "{{ .Values.common.name }}-images"
            mountPath: "/opt/app/uploads"
        resources:
          limits: {{ .Values.api.limits | toYaml | nindent 12 }}
        ports:
        - containerPort: {{ .Values.api.targetPort }}
      volumes:
        - name: "{{ .Values.common.name }}-images"
          persistentVolumeClaim:
            claimName: "{{ .Values.common.name }}-{{ .Values.api.name }}-pvc"