apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.common.name }}-{{ .Values.mq.name }}-clusterip"
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.mq.component }}
  ports:
  - port: {{ .Values.mq.port }}
    targetPort: {{ .Values.mq.targetPort }}
    protocol: TCP
