apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.common.name }}-{{ .Values.api.name }}-clusterip"
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.api.component }}
  ports:
  - port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.targetPort }}
