apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.common.name }}-{{ .Values.processor.name }}-clusterip"
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.processor.component }}
  ports:
  - port: {{ .Values.processor.port }}
    targetPort: {{ .Values.processor.targetPort }}
